build:
  maxIssues: 0

complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 30
    thresholdInInterfaces: 20

style:
  MaxLineLength:
    maxLineLength: 120
  WildcardImport:
    active: false
  MagicNumber:
    active: false
  ForbiddenComment:
    active: false
  ReturnCount:
    max: 5

naming:
  FunctionNaming:
    ignoreAnnotated:
      - "Composable"
  TopLevelPropertyNaming:
    constantPattern: "[A-Za-z][_A-Za-z0-9]*"
